apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "user-service.name" . }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: user-service.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "user-service.name" . }}
                port:
                  number: 8080
