apiVersion: v1
kind: Service
metadata:
  name: {{ include "user-service.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "user-service.name" . }}
spec:
  selector:
    app: {{ include "user-service.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
